# Generated by Django 3.1.7 on 2021-03-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='detail',
            new_name='about',
        ),
        migrations.AddField(
            model_name='react',
            name='address',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
