# Generated by Django 3.1.7 on 2021-03-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210318_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='name',
        ),
        migrations.AddField(
            model_name='react',
            name='contact',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='react',
            name='f_name',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='react',
            name='l_name',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
